# ==============================================================================
# HeadUnit OS — Fast PC-to-Pi Deployment Tool
# Compiles on Windows host and deploys directly to the Raspberry Pi in seconds.
# ==============================================================================

param (
    [string]$PiHost = "10.42.0.109",
    [string]$PiUser = "webcap",
    [int]$PiPort = 22
)

$ErrorActionPreference = "Stop"
$ProjectDir = (Get-Item $PSScriptRoot).Parent.FullName

Write-Host "=================================================================" -ForegroundColor Cyan
Write-Host "  HeadUnit OS — Fast PC-to-Pi Deployment Tool" -ForegroundColor Cyan
Write-Host "  Target: ${PiUser}@${PiHost}:${PiPort}" -ForegroundColor Cyan
Write-Host "=================================================================" -ForegroundColor Cyan
Write-Host ""

# 1. Update Build Version
Write-Host "[1/4] Calculating build number..." -ForegroundColor Cyan
$commitCount = (git rev-list --count HEAD).Trim()
$pubspecPath = Join-Path $ProjectDir "pubspec.yaml"
$pubspecLines = Get-Content $pubspecPath
for ($i = 0; $i -lt $pubspecLines.Count; $i++) {
    if ($pubspecLines[$i] -match '^version:\s*([^+]+)') {
        $verName = $matches[1].Trim()
        $pubspecLines[$i] = "version: ${verName}+${commitCount}"
        break
    }
}
$pubspecLines | Set-Content $pubspecPath
Write-Host "Updated pubspec.yaml with commit count ${commitCount}." -ForegroundColor Green

# Generate lib/version.dart
$versionDart = Join-Path $ProjectDir "lib\version.dart"
"// Generated by deploy_to_pi.ps1. Do not edit manually.`nconst String buildVersion = '${verName}+${commitCount}';" | Set-Content -Path $versionDart

# 2. Build Flutter Bundle on PC
Write-Host ""
Write-Host "[2/4] Building Flutter asset bundle on PC..." -ForegroundColor Cyan
Push-Location $ProjectDir
try {
    flutter build bundle
} finally {
    Pop-Location
}
Write-Host "Asset bundle compiled successfully." -ForegroundColor Green

# Ensure icudtl.dat is copied into assets
$assetsDir = Join-Path $ProjectDir "build\flutter_assets"
$icuSource = Join-Path $ProjectDir "arm64_engine\icudtl.dat"
if (-not (Test-Path $icuSource)) {
    $flutterSdkDir = Split-Path (Split-Path (Get-Command flutter).Source -Parent) -Parent
    $icuSource = Join-Path $flutterSdkDir "bin\cache\artifacts\engine\windows-x64\icudtl.dat"
}
if (Test-Path $icuSource) {
    Copy-Item $icuSource (Join-Path $assetsDir "icudtl.dat") -Force
}

# 3. Transfer Bundle and Matching ARM64 Engine to Raspberry Pi
Write-Host ""
Write-Host "[3/4] Transferring bundle to Raspberry Pi (${PiHost})..." -ForegroundColor Cyan

# Create remote destination directory
ssh -p $PiPort "${PiUser}@${PiHost}" "mkdir -p ~/headunit-os/build/flutter_assets"

# Copy matching ARM64 engine if present
$arm64Engine = Join-Path $ProjectDir "arm64_engine\libflutter_engine.so"
if (Test-Path $arm64Engine) {
    Write-Host "Copying native matching ARM64 libflutter_engine.so..." -ForegroundColor Yellow
    scp -P $PiPort $arm64Engine "${PiUser}@${PiHost}:/tmp/libflutter_engine.so"
    ssh -p $PiPort "${PiUser}@${PiHost}" "sudo cp /tmp/libflutter_engine.so /usr/lib/libflutter_engine.so; sudo cp /tmp/libflutter_engine.so /usr/local/lib/libflutter_engine.so; sudo cp /tmp/libflutter_engine.so ~/headunit-os/build/flutter_assets/; sudo ldconfig; rm -f /tmp/libflutter_engine.so"
}

# SCP the flutter_assets folder to Pi
Write-Host "Copying assets folder..." -ForegroundColor Cyan
scp -P $PiPort -r "${assetsDir}\*" "${PiUser}@${PiHost}:~/headunit-os/build/flutter_assets/"

Write-Host "Transfer complete." -ForegroundColor Green

# 4. Restart HeadUnit OS Kiosk Service
Write-Host ""
Write-Host "[4/4] Restarting HeadUnit OS Kiosk Service on Pi..." -ForegroundColor Cyan
ssh -p $PiPort "${PiUser}@${PiHost}" "sudo systemctl restart headunit.service"

Write-Host ""
Write-Host "=================================================================" -ForegroundColor Green
Write-Host "Successfully Deployed to Raspberry Pi!" -ForegroundColor Green
Write-Host "=================================================================" -ForegroundColor Green
